---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: woogidi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: woogidi
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: jtaylor32/woogidi-woogidi-woogidi
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: http_proxy
          value: $(NODE_NAME):4140
        ports:
        - name: service
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: woogidi
spec:
  selector:
    app: woogidi
  clusterIP: None
  ports:
  - name: http
    port: 8080
